name: crud_flutter
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_staggered_grid_view: ^0.6.1
  http: ^0.13.4
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/bag.png
    - assets/interior.png
    - assets/eksterior.png
    - assets/enginebay.png
    - assets/kacamobil.png
    - assets/velg&ban.png
    - assets/aa.png
    - assets/logo_eviasi.png
